### ISSUE TITLE
event owner permissions vs collaborator permissions vs org permissions

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#426] opened 2020-11-19 17:26 UTC
Note - less urgent bug because unlikely to happen much...

Need to make sure that event owner permission overrides any collaborator permissions. Someone who owned an event added herself as a read only collaborator to that event and suddenly couldn't edit her own event. 

Same goes for any role within the org or parent org that should have read/write access to an event - that should override collaborator settings. For example, if org admin gets added as a read collaborator, they should still be able to edit because they are org admin.
That said, if a partner user in the same org who only has read access to an events in their org gets added as a read/write collaborator, then the collaborator status that has elevated privileges should override.

**Comment by aaronstephenson** [comment] 2020-11-23 22:16
@JChipault I just implemented a small code change in the test environment that will silently remove the event owner from any request to add the event owner to either collaborator list (for example, when creating an event, the creator has 4 people including herself in the write collaborators list, the code will remove the creator's ID from that list and just add the other 3). This change will prevent this situation in the future. Let me know your thoughts on that and whether I should promote it to production.

There remains however the larger problem of the non-event owner users in the same org as the event owner being added as collaborators. This will take much longer to fix because the permission assessments happen in dozens of places throughout the codebase.

**Comment by aaronstephenson** [comment] 2020-11-24 20:25
@JChipault I am unable to reproduce this issue locally.

In the client, I logged in as a partner role, I created an event (and added myself as read collaborator during that create). After the event successfully created, I was still able to go to the event and edit the event itself (fields like event_reference) and child objects like locations and diagnoses.

Can you give me the full scenario that this user reported? The specific things (s)he did, the fields (s)he tried to edit. Was there an error message, or did an edit just "silently" not succeed?

**Comment by JChipault** [comment] 2020-11-24 20:44
Hey @aaronstephenson - sorry I didn't reply earlier. I saw "I just implemented a small code change..." and though "cool! he fixed it!" and was thinking I just needed to test it at some point. But I see now, now that I read your whole comment, that you had some questions. I'll dig into this more and get back you. I'll probably also talk to @nbaertlein because this is a lower priority bug so not sure how much time we want to spend on it. Appreciate you taking a look and coming up with a possible fix for the event owner issue though!!

**Comment by JChipault** [comment] 2020-11-24 21:40
First message from user Lorna McCallister in FL: 
"For WHISPers event 200775 (event reference 180122_Loons), I must have accidentally selected the circle we made (which is you, Lisa, and myself) in the "read only access" collaborators section, instead of the "read and write access" section, when I originally created the event. I am still able to edit most of the event which is good. However, I cannot change the collaborators sections. I can't delete our contacts from the "read only" section or add them to the "read and write access section" without getting an error that I do not have permission to do that. I also cannot add in our SCWDS collaborators now to the "read only" section without getting the same error that I don't have permission to do that." 

I (Jenny) tried changing the event from "complete" to "incomplete", thinking that might fix things, to which Lorna replied:
"I opened the event and saw that it is still set to "incomplete". The changes that you said you made were saved in the event.

So, I tried to delete myself from the "read only access" section by using the red "-" button, and I received the following error: Error. Collaborator list not updated. Error message: {"detail":"You do not have permission to perform this action."} . However, it appears that I do get deleted from that section. I also tried to add myself to the "read and write access" section using the "add individual" button, and I received the same error message: Error. Collaborator list not updated. Error message: {"detail":"You do not have permission to perform this action."}. Again it showed that this had worked and I was added to this section. But, when I close out the page and re-open it to see if the changes truly stick, the page goes back to how it was previously with me in the read-only section, so my edits are not saving.

I also tried to add other SCWDS members to the "read only access" section using the "add individual" button and received the same error message: Error. Collaborator list not updated. Error message: {"detail":"You do not have permission to perform this action."}. Like with trying to add and delete myself, their [collaborator names] would appear to be added, but would then disappear if the event was re-opened. 

Interestingly, I tried adding in event level comments and I was allowed to do that. I was also able to change location level comments. However, I get the same error message when I try to change the event to "visible to the public" or "complete". So it appears that my permissions are limited depending on what section I am editing."

So then I (Jenny) removed Lorna as a read-only collaborator and she reported that she was then able to edit the fields she hadn't been able to previously edit.

**Comment by JChipault** [comment] 2020-11-24 21:42
I think I'm ok with the silent fail when an event owner adds themselves as a read or read/write collaborator (either as an individual or as part of a circle)

**Comment by JChipault** [comment] 2020-11-24 21:45
Silent fail would happen in both create event and event details page, right?

**Comment by aaronstephenson** [comment] 2020-11-24 21:51
Yes. Though I wouldn't call it a "fail" :) more of an "ignore", since any other users in the list would be added.

Thanks for the details from the user, they are extremely useful! It appears that the problems are in the many-to-many related objects (collaborators, contact), but not in one-to-many related objects (locations, species).  And also event.complete, which has its own dedicated code block because it has so many business rules tied to it. I will dig back in to the code with these details in mind.

**Comment by aaronstephenson** [comment] 2021-01-06 20:45
I was able to look into this and recreate Lorna's scenario. There are two things going on here.

1. 
>So, I tried to delete myself from the "read only access" section by using the red "-" button, and I received the following error: Error. Collaborator list not updated. Error message: {"detail":"You do not have permission to perform this action."} . However, it appears that I do get deleted from that section. I also tried to add myself to the "read and write access" section using the "add individual" button, and I received the same error message: Error. Collaborator list not updated. Error message: {"detail":"You do not have permission to perform this action."}. Again it showed that this had worked and I was added to this section. But, when I close out the page and re-open it to see if the changes truly stick, the page goes back to how it was previously with me in the read-only section, so my edits are not saving.

>I also tried to add other SCWDS members to the "read only access" section using the "add individual" button and received the same error message: Error. Collaborator list not updated. Error message: {"detail":"You do not have permission to perform this action."}. Like with trying to add and delete myself, their [collaborator names] would appear to be added, but would then disappear if the event was re-opened.

This part, where she gets a validation error saying she doesn't have permission to do an action, yet the collaborator names disappear from the screen, is a disconnect between the client app and the API. The client code assumes that the request will succeed, so locally removes the names from the collaborator list in the client app. However, the client app is then out of sync with the API/DB, because the names were never removed from the API/DB. So, maybe something to take a look at @BlakeDraper.

2.
>However, I get the same error message when I try to change the event to "visible to the public" or "complete".

This part is the intended behavior, and Lorna being in the collaborator list has no impact here; no one, not even Admins and event owners, can edit events when `complete` = True. I think her confusion might have been caused by the error message, so I will rephrase that to make it clearer. In order to edit a complete event, an Admin or the event owner either needs to set `complete` to False and then come back to make the edits, OR set `complete` to False and make the edits at the same time (that is, submit the edits and the `complete` = False in the same request).

I tried several different scenarios when the event is complete (set `public` to True, set `complete` to False, set `public` to True _and_ `complete` to False) and I get the expected response each time (failure, success, success).

**Comment by JChipault** [comment] 2021-01-06 23:19
1 - This might be fixed for the event owners now because the reason she didn't have permissions is because her access as a read only collaborator was overriding her access as the event owner. But now I see you have the "ignore" feature working (at least on the test site), wherein if an event owner tries to add themselves as a collaborator, then it just doesn't stick. Since she now can't make herself read-only, she'd have the ability to remove/add other collaborators in her org without getting that message.

2 - similar thoughts as 1... it wasn't that she was trying to change other fields while the event was marked "complete," it was that she was trying to change it from "incomplete" to "complete" while she was a read only collaborator. She can't accidentally make herself read only anymore.

That said, while the event owner can't become a read only collaborator anymore thanks to your "ignore" fix, it's still possible for other people in their org to become collaborators, so I think we're left with figuring out this part of my original ticket (eventually):
_Same goes for any role within the org or parent org that should have read/write access to an event - that should override collaborator settings. For example, if org admin gets added as a read collaborator, they should still be able to edit because they are org admin.
That said, if a partner user in the same org who only has read access to an events in their org gets added as a read/write collaborator, then the collaborator status that has elevated privileges should override._

**Comment by aaronstephenson** [comment] 2021-01-07 20:12
Yes. That is a larger problem and will take time to investigate.

**Comment by aaronstephenson** [comment] 2021-01-08 22:17
I've been looking into this all day using multiple scenarios, and I can't find a single scenario where the code doesn't perform as expected. Here's what I tried, all for Event 200775 with users from Organization 214 (Florida Fish and Wildlife Conservation Commission - Fish and Wildlife Research Institute - Gainesville):

1. Added the system admin (user 1) to the event's Read Collaborators list, confirmed user could still edit event attributes and even the collaborators list. User was not blocked from editing despite being in the Read Collab list.

2. Created a new user in org 214 with role 5 (basic Partner). Confirmed user could not edit any event attributes. Added this user to the event's Write Collaborators list, confirmed user could then edit attributes.

3. Used an existing user in org 214 who has role 3 (Partner Admin). Confirmed user could edit any event attributes. Added this user to the event's Read Collaborators list, confirmed user could still edit event attributes and even the collaborators list. User was not blocked from editing despite being in the Read Collab list.

4. Added the event owner (Lorna) to the event's Read Collab list, confirmed user could still edit event attributes and even the collaborators list. User was not blocked from editing despite being in the Read Collab list. I could even toggle the event `complete` value from false to true to false without any errors, again while she was in the Read Collab list.

So this leaves me completely perplexed about the original issue report, since in every test I did, the user had exactly the permissions that one would expect (namely, the user's role and event ownership status took precedence over collab list membership, except the basic Partner user who got elevate permissions by being in the Write Collab list, that is, admin, Partner Admin, event owner could all edit the event despite being in the Read Collab list).

When you wrote
>Someone who owned an event added herself as a read only collaborator to that event and suddenly couldn't edit her own event.

I took that to mean that she couldn't edit _anything_ in that event, but was that truly the case? Or was it that she could not edit only some things, or only one thing? Also, what was the complete/incomplete status of the event when she attempted to make edits?

Note that I did these tests on my laptop, which is in the same state as the test environment.

**Comment by JChipault** [comment] 2021-01-12 19:32
Based on re-reading Lorna's email, looks like it went like this.

1) The event she created was marked as complete with herself (accidentally) as a read-only collaborator.
2) She then went to the event details page and tried to remove herself as a read-only collaborator and could not. Lorna says, "I am still able to edit most of the event which is good. However, I cannot change the collaborators sections. I can't delete our contacts from the "read only" section or add them to the "read and write access section" without getting an error that I do not have permission to do that."

The error she was getting didn't tell her that she couldn't change something because the event was marked complete, but it was telling her she didn't have permissions to change that section. Since she said she could edit most of the event, she was likely able to toggle it between complete/incomplete at this point (?), although maybe when she said "I am still able to edit most of the event" it was really only comments (which you can add after an event is marked complete, by design) - I'm not sure on this detail.

3) Even though she wasn't getting the normal message that says something along the lines of "hey, you can't edit anything unless you toggle this event from complete to incomplete", I went ahead and logged in to my jchipault account and changed the event from "complete" to "incomplete" and asked her to look at it again.

4) She reported that she can see that I changed it to incomplete but she was still being told that she didn't have permissions to add or remove collaborators. So this was definitely when the event was incomplete and she was still listed as a read-only collaborator. She was able to add event comments and location comments, but was told she didn't have permissions to change it from "incomplete" to "complete" and told she didn't have permissions to change it from "not visible to public" to "visible to public". So, in summary, seems she's unable to edit collaborators or edit event-level data (complete and visibility) when the event was marked as incomplete and she was a read-only collaborator.

5) When she reported that she was still having problems after I had changed the event to "incomplete" for her, I next went back into the event and removed her from the read-only collaborator section.

6) Lorna goes back to the event and reports that she can now edit all the fields she expects to be able to edit and is no longer getting the error message about permissions since I've removed her as a read-only collaborator.

**Comment by JChipault** [comment] 2021-01-12 19:34
I just tried to recreate the scenario that Lorna found herself in by logging in to the abilenetest account and created a complete event that was not visible to the public with abilenetest as a read-only collaborator, but now that you've got that "ignore" function coded, when the event saved it did not save abilenetest as a read-only collaborator on the event they created.

**Comment by JChipault** [comment] 2021-01-12 19:37
Everything you report regarding your checks sounds good. I'm not sure how you ran your scenario 4 though because that's when I hit the "ignore" fix. Maybe you turned the "ignore" off when you ran your scenario 4 and added Lorna as a read-only collaborator on an event she owned? Or was it the ignore fix that made her just slide out of that read-only spot??

**Comment by aaronstephenson** [comment] 2021-01-12 19:40
For my scenario 4, I manually added the user ID in the read collaborator DB table, effectively circumventing the "ignore" feature (since that only happens during an event create or update via the API).

**Comment by JChipault** [comment] 2021-01-12 19:41
So maybe we're good then?

**Comment by JChipault** [comment] 2021-01-12 19:42
maybe it was just the event owner/read-collaborator combo that was causing problems and you've fixed that with the "ignore" fix

**Comment by JChipault** [comment] 2021-01-12 19:47
although you tried the event owner/read-collaborator combo and it seemed fine... which was why I was going to try the specific scenario of creating a complete and private event where the owner was a read-collaborator, thinking maybe the "complete" and "visibility" settings mattered? But if one can't add themselves as a read-only anymore, then that's moot

**Comment by aaronstephenson** [comment] 2021-01-12 19:52
On the test server, I could disable that bit of code that I wrote to do the "ignore", then you could test the scenario. Would take me less than a minute.

**Comment by JChipault** [comment] 2021-01-12 19:55
sounds good

**Comment by aaronstephenson** [comment] 2021-01-12 20:01
Changed, event creator can now add self to collaborator lists on the test server. Give it a try.

**Comment by JChipault** [comment] 2021-01-12 20:19
I can't recreate the problem.

**Comment by aaronstephenson** [comment] 2021-01-12 20:26
Yeah, I couldn't either, hence my perplexion.

I dunno. I'm kind of feeling like we're chasing ghosts with this one. I say we just move on, but keep an eye out for users reporting situations like this (and taking copious notes if they do).

**Comment by JChipault** [comment] 2021-01-12 20:26
Maybe keep the "ignore" fix in the code, but I think we can close this ticket.

**Comment by aaronstephenson** [comment] 2021-01-12 20:30
Code on the test server reverted so that the "ignore" fix is live again. Closing issue but will keep an eye out for similar reports.

**Closed by aaronstephenson** 2021-01-12 20:30 UTC
