### ISSUE TITLE
Duplicate timed notifications

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#413] opened 2020-10-22 20:29 UTC
Seeing duplicates of overnight notifications.  Examples include whispers_notification ids: 8842 & 8847; 8843 & 8848; 8877 & 8882; 8874 & 8881.  My email confirms they were sent at the same time @ 3am.

**Comment by nbaertlein** [comment] 2020-10-22 20:42
Also found a notification that was repeated 12 times.  Haven't confirmed actual email receipt with Kim yet.  Please see whispers_notification ids: 8858,  8859,  8862,  8863,  8866,  8867,  8868,  8869,  8870,  8871,  8872,  8873.

**Comment by aaronstephenson** [comment] 2020-10-27 00:07
The notification that was repeated 12 times was caused by the structure of the Django ORM query in the Custom Notification task code, I have now added a "distinct" clause to it and confirmed that there are no more duplicates when I test. The other duplicates you report I cannot reproduce despite trying several scenarios; let me know if you see it happen again.

**Comment by aaronstephenson** [comment] 2020-10-27 00:11
Fixed in 2.0.6 c4061cc3

**Comment by JChipault** [comment] 2020-10-30 13:27
@aaronstephenson @BlakeDraper  I was expecting standard notifications in the wee hours of 10/30 for 170933 (I updated my event yesterday), 170934 (Neil created yesterday), and 170935 (Neil created yesterday) and received none of those. Good news: there aren't duplicates...  Bad news: there aren't anything.

I think Neil is out today. Let me know if there's any questions or any further testing I should set up today to run something overnight. Thanks!

**Comment by aaronstephenson** [comment] 2020-10-30 15:19
I had the `yesterday` variable set to 5 days previous. Forgot to reset it after I debugged the duplicates problem a few days back.

Fixed in 2.0.7 e32b8fb

**Closed by aaronstephenson** 2020-10-30 15:19 UTC
