### ISSUE TITLE
can't create event from partner account with service request

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#425] opened 2020-11-18 20:03 UTC
**Describe the bug**
This came up because our partners have been having an issue on the live site and I was able to reproduce some issues on the test site. Looks like the crux of it is that a partner can't create an event that includes a service request. I can create events without service requests from a partner account and I can add a service request from the event details page, but I can't create an event with a service request.

**To Reproduce**
When I created an event from my jchipault account in the test site (v2.15.11) , it went through no problem (170941).

When I tried to create an event in the test site from my abilenetest user account and copy what our Wisconsin DNR partner (Nancy Businga) did in the live site this morning (plus add a service request because she said she did have a service request and comment), I got this:
![image](https://user-images.githubusercontent.com/49287076/99581323-38409a80-29a6-11eb-8db6-51a2de082345.png)

Then I removed the service request and hit Save Event again and it went through (event ID 170942).

I repeated the create event process from the abilenetest account with different data but including a service request and comment and got this error:
![image](https://user-images.githubusercontent.com/49287076/99581378-54443c00-29a6-11eb-9bd7-563131aedce7.png)

When I deleted the service request comment (but kept the service request) and hit Save Event, I got this same error message again.

When I switched off of making a diagnostic request, it went through (170945). So seems 170943 was created the first time I got this "non_field_errors" error message and 170944 was created the second time I got the "non_field_errors" error message.

**Comment by BlakeDraper** [comment] 2020-11-20 19:45
@aaronstephenson This is the error when submitting an event with service request using the `abilenetest` account on test DB (partner role).
![image](https://user-images.githubusercontent.com/6978380/99842843-2ee63800-2b36-11eb-8823-d74b2ce61b6d.png)

submission JSON:
```
{
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": null,
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    4
  ],
  "new_service_request": {
    "request_type": 1,
    "new_comments": [
      {
        "comment": "test comment"
      }
    ]
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2020-11-03",
      "end_date": "2020-11-11",
      "country": "30",
      "administrative_level_one": 51,
      "administrative_level_two": 3043,
      "latitude": null,
      "longitude": null,
      "land_ownership": "4",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "test test test ",
      "history": "",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 247,
          "population_count": null,
          "sick_count": null,
          "dead_count": 3,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}
```

**Comment by aaronstephenson** [comment] 2020-11-20 22:08
Fixed in 2.0.11 6a53f67

**Closed by aaronstephenson** 2020-11-20 22:08 UTC

**Comment by JChipault** [comment] 2020-12-01 17:43
@aaronstephenson tested yesterday in test site and got JSON error but this seems to be working in the live site (based on not getting further complaints or duplicated events entered)... when test gets pushed to live, this will still work in live, correct??

**Comment by aaronstephenson** [comment] 2020-12-01 22:00
@JChipault this fix was pushed to prod at the same time I pushed to test; it is "live". Test is actually ahead of prod by one commit because I implemented the [code](https://github.com/USGS-WiM/whispersservices/issues/426#issuecomment-732457424) that prevents the event owner from adding his/herself as a collaborator (issue #426).

What specific JSON error are you getting?

**Comment by JChipault** [comment] 2020-12-01 22:22
Well, of course I didn't grab a screen shot when I hit that JSON error last night. I messed up there - sorry. It does look like the event went through despite the error message I got: https://whisperstest.wim.usgs.gov/event/170953. But there is no service request information showing on the front end and I know I submitted a request. There was also no service request notification email sent to nwhc-epi@usgs.gov.

I tried again tonight from this same account (abilenetest) and was able to create two events with a service request without a problem - event saved, service request saved, and service request notification was sent.

Does knowing that it was 170953 that was problematic provide any hints?

**Comment by aaronstephenson** [comment] 2020-12-02 20:09
It looks like celerybeat on the test server hasn't been working since November 5 (per the timestamp on the logs), despite the daemon status reporting "active". I just restarted it and now there are dozens of new notifications, likely from a backlog in the rabbitmq message queue.

celerybeat only affects the nightly notification processes though. I don't have an explanation for the JSON error you saw and the lack of notification for a service request, since those only use celery, aside from observing that Patrick at EROS was doing a bunch of patches and network changes, including changing the server hostnames and domain status, in November that might have affected this. Let me know right away if you encounter that problem again, with details of the error message.

**Comment by JChipault** [comment] 2020-12-15 17:59
Tried creating a complete event with a service request from jchipault account in test site. Got JSON error (also see form values at end of this comment).
![image](https://user-images.githubusercontent.com/49287076/102253152-980a6280-3ecc-11eb-845a-2d690a5b8b53.png)

Sometimes when we get an error message on the front end, the event actually saves, but it doesn't seemed to have saved in this case. 

I tried again to create an event from the same account with similar types of data but left OFF the service request and that event saved just fine (170963)

Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": true,
  "public": true,
  "staff": null,
  "event_status": "1",
  "quality_check": null,
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 1,
    "new_comments": [
      {
        "comment": "asdfasdf"
      }
    ]
  },
  "new_event_diagnoses": [
    {
      "diagnosis": "31"
    }
  ],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2020-12-14",
      "end_date": "2020-12-15",
      "country": "30",
      "administrative_level_one": 24,
      "administrative_level_two": 1228,
      "latitude": null,
      "longitude": null,
      "land_ownership": "7",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "aere",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 1202,
          "population_count": null,
          "sick_count": null,
          "dead_count": 1,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": [
            {
              "diagnosis": 31,
              "cause": 1,
              "basis": 1,
              "suspect": true,
              "tested_count": null,
              "diagnosis_count": null,
              "positive_count": null,
              "suspect_count": null,
              "pooled": false,
              "new_species_diagnosis_organizations": []
            }
          ]
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": []
}

**Comment by JChipault** [comment] 2020-12-15 18:51
@aaronstephenson I should note that I've been creating events with service requests pretty frequently over the past week or so to try to reproduce this bug. I just tried again (about an hour after i hit the last error) with a similar type of event and it went through just fine (170964, which is a complete event with a species diagnosis and an event diagnosis and with a service request and service request comment). Could it be something with servers or internet coverage??

**Comment by BlakeDraper** [comment] 2020-12-18 17:21
@JChipault I have been testing this myself and cannot reproduce the error you show. Sounds like you are having a similar experience? Your error shows that the response back from the server is not JSON, as the API is set to respond with, which does suggest (though not prove) that it is a server issue, i.e. an EROS thing.  Can we maintain this as a monitor situation, or is it frequent enough to warrant a deep dive?

**Comment by JChipault** [comment] 2020-12-21 15:42
Neil's 12/18 response via email: "Given its elusiveness and likely server-side issue I agree we should move on and monitor.  Long term, I'm wondering if we could look into error logging..."
Jenny's confused by Blake's "Your error shows that the response back from the server is not JSON" because it looks like a JSON error to me, but I'm sure I'm just not understanding the technical stuff here. Overall, yes, it doesn't reproduce consistently so I'm ok letting it sit.

**Comment by aaronstephenson** [comment] 2020-12-23 23:10
I tried to reproduce this bug just now (new event with a service request), using the test web client app and also a REST API client, and both attempts succeeded without error.

@JChipault what Blake means is that the content received from the API in the case of that error is not JSON (likely HTML instead), which is why the error message says "syntax error: JSON.parse"; in other words, the client app cannot parse any JSON to show an error message from the API because the response isn't JSON. If it was JSON, the content would have parsed and appeared in the toast message (like one of the earlier examples you posted here, "non-field errors: you do not have permission..."). I hope that helps, let me know if that's clear as mud.

Something that would really help in debugging this would be the actual content of the response from the API. You can see it by using the network tab of the browser developer tools (shortcut is just the F12 key), it would look something like this (the bottom half of this screen capture):
![image](https://user-images.githubusercontent.com/8713712/103042913-c200fc00-4540-11eb-83de-62e519f2d94e.png)

(the error line would be fairly obvious, the text in the left column would be red and the status value would be something in the 400s or 500s (as opposed to the 200s or 300s), and the response body (the right column) would likely be HTML instead of the JSON in this example)
