### ISSUE TITLE
Stale event notifications not being generated

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#414] opened 2020-10-23 15:21 UTC
We've created and edited a number of events these past couple weeks however we have not received any stale event notifications.  Periodicity via the configuration table is set at 1, 2, and 5 days.  The last stale event notification was created on 10/8/2020.

**Comment by aaronstephenson** [comment] 2020-10-26 22:11
This was caused by a single variable accessor that I forgot to remove during the refactor. Easy fix, coming shortly.

**Comment by aaronstephenson** [comment] 2020-10-27 00:11
Fixed in 2.0.6 c4061cc3

**Closed by aaronstephenson** 2020-10-27 00:11 UTC
