### ISSUE TITLE
Add Pacific Flyway to Hawaii events

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#505] opened 2021-08-16 16:33 UTC
**Describe the bug**
Aaron's code has this "# HI is not in a flyway, so assign it to Pacific ("Include all of Hawaii in with Pacific Americas")" but when I create an event in Hawaii, it doesn't get marked as any flyway

**To Reproduce**
1. Create an Event
2. Select state of Hawaii
3. Note that no Flyway gets assigned

Screen shot from https://whisperstest.wim.usgs.gov/event/171036:
![image](https://user-images.githubusercontent.com/49287076/129597874-6b963c21-862e-427d-8839-07c91ffb7c28.png)

**Comment by aaronstephenson** [comment] 2021-08-30 20:45
@JChipault I took a look into this, and the flyway is being properly assigned to Pacific. Take a look:
https://whisperstest.wim.usgs.gov/api/eventdetails/171036/

![image](https://user-images.githubusercontent.com/8713712/131402947-6b0aa853-7918-4380-9949-9c418773cd67.png)

I think the trouble here might be that the client app is trying to read the flyway as an attribute of the event location, when it's actually a related object in an array (a 1:N relate between the event location and flyways).

@BlakeDraper can you take a look?

**Comment by BlakeDraper** [comment] 2021-08-31 20:15
I looked into this and the client does seem to be parsing the server data correctly and it does in fact display the Flyway for the event example above. In other words: this event does have its flyway, and it displays on the client. 

However, I did Jenny's steps to recreate (create an event in Hawaii) and found it did not get populated with a a flyway. So it does seem something is up with the assignment process. For reference my new test event on the test DB is https://whisperstest.wim.usgs.gov/api/eventdetails/171045/.

**Comment by aaronstephenson** [comment] 2021-08-31 21:34
When I create an event in the API (using Insomnia), the flyway gets assigned. Is there something in the way the client submits the data that might be different? What specific location data did you choose?

**Comment by BlakeDraper** [comment] 2021-08-31 22:28
I'll leave you the exact JSON body to see if you can find the problem. The below JSON was created in the client app and created an event w/out flyways populated. I then took this exact body and submitted it using Insomnia to the same result. These created events 171048 and 171049 in the test DB. So there must be something critically different about your test submission - but this is still passing as a valid POST request. Notably, this does not include any lat/long as that is not required.

```
{
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": null,
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2021-08-03",
      "end_date": "2021-08-18",
      "country": "30",
      "administrative_level_one": 13,
      "administrative_level_two": 545,
      "latitude": null,
      "longitude": null,
      "land_ownership": "6",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "this bird should not be in Hawaii",
      "history": "",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 1221,
          "population_count": 5,
          "sick_count": null,
          "dead_count": 2,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}
```

**Comment by aaronstephenson** [comment] 2021-09-01 15:04
Thanks for the JSON. The critical difference between our attempts is that yours does not include lat/lng, which causes the flyway determination to follow a different branch where a temporary lat/lng (the county centroid) is used to look up the flyway. Which, in the case of Hawaii, doesn't work as intended because the FWS web service doesn't include Hawaii. I see now that the code snippet that Jenny referenced is in the wrong place, so I have rearranged things in branch 505 (2729f30c) to ensure Hawaii is properly assigned. I will include this change in the next release.

**Comment by aaronstephenson** [comment] 2021-09-22 01:39
Feature added in v2.1.7 (9f5eb70) and published to the test and production environment.

**Closed by aaronstephenson** 2021-09-22 01:39 UTC
